chmod +x scripts/experimentSetUp.sh 
./scripts/experimentSetUp.sh experiments/19PatchSize 

python3 train.py --patchSize 19 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 19 --device cuda  --softLabels    >> experiments/19PatchSize/L3SFexp49.log; wait;
python3 train.py --patchSize 19 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 19 --device cuda  --softLabels    >> experiments/19PatchSize/L3SFexp50.log; wait;
python3 train.py --patchSize 19 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 19 --device cuda  --softLabels    >> experiments/19PatchSize/L3SFexp51.log; wait;
python3 train.py --patchSize 19 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp52.log; wait;

python3 train.py --patchSize 19 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp53.log; wait;
python3 train.py --patchSize 19 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp54.log; wait;
python3 train.py --patchSize 19 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp55.log; wait;
python3 train.py --patchSize 19 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp56.log; wait;

python3 train.py --patchSize 19 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp57.log; wait;
python3 train.py --patchSize 19 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp58.log; wait;
python3 train.py --patchSize 19 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp59.log; wait;
python3 train.py --patchSize 19 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp60.log; wait;

python3 train.py --patchSize 19 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp61.log; wait;
python3 train.py --patchSize 19 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp62.log; wait;
python3 train.py --patchSize 19 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp63.log; wait;
python3 train.py --patchSize 19 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/19PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 19 --device cuda --softLabels    >> experiments/19PatchSize/L3SFexp64.log; wait;