chmod +x scripts/experimentSetUp.sh 
./scripts/experimentSetUp.sh experiments/17PatchSize 

python3 train.py --patchSize 17 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda  --softLabels    >> experiments/17PatchSize/L3SFexp33.log ; wait;
python3 train.py --patchSize 17 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda  --softLabels    >> experiments/17PatchSize/L3SFexp34.log; wait;
python3 train.py --patchSize 17 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda  --softLabels    >> experiments/17PatchSize/L3SFexp35.log; wait;
python3 train.py --patchSize 17 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp36.log; wait;

python3 train.py --patchSize 17 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp37.log; wait;
python3 train.py --patchSize 17 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp38.log; wait;
python3 train.py --patchSize 17 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp39.log; wait;
python3 train.py --patchSize 17 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp40.log; wait;

python3 train.py --patchSize 17 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp41.log; wait;
python3 train.py --patchSize 17 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp42.log; wait;
python3 train.py --patchSize 17 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp43.log; wait;
python3 train.py --patchSize 17 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp44.log; wait;

python3 train.py --patchSize 17 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp45.log; wait;
python3 train.py --patchSize 17 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp46.log; wait;
python3 train.py --patchSize 17 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp47.log; wait;
python3 train.py --patchSize 17 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3   --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/L3SFexp48.log; wait;