chmod +x scripts/experimentSetUp.sh 
./scripts/experimentSetUp.sh experiments/17PatchSize 

python3 train.py --patchSize 17 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda  --softLabels    >> experiments/17PatchSize/PolyUexp33.log ; wait;
python3 train.py --patchSize 17 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda  --softLabels    >> experiments/17PatchSize/PolyUexp34.log; wait;
python3 train.py --patchSize 17 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda  --softLabels    >> experiments/17PatchSize/PolyUexp35.log; wait;
python3 train.py --patchSize 17 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp36.log; wait;

python3 train.py --patchSize 17 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp37.log; wait;
python3 train.py --patchSize 17 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp38.log; wait;
python3 train.py --patchSize 17 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp39.log; wait;
python3 train.py --patchSize 17 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp40.log; wait;

python3 train.py --patchSize 17 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp41.log; wait;
python3 train.py --patchSize 17 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp42.log; wait;
python3 train.py --patchSize 17 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp43.log; wait;
python3 train.py --patchSize 17 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp44.log; wait;

python3 train.py --patchSize 17 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp45.log; wait;
python3 train.py --patchSize 17 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp46.log; wait;
python3 train.py --patchSize 17 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp47.log; wait;
python3 train.py --patchSize 17 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/17PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 17 --device cuda --softLabels    >> experiments/17PatchSize/PolyUexp48.log; wait;