chmod +x scripts/experimentSetUp.sh 
./scripts/experimentSetUp.sh experiments/13PatchSize 

python3 train.py --patchSize 13 --poreRadius 3 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 13 --device cuda  --softLabels >> experiments/13PatchSize/PolyUexp1.log; wait;
python3 train.py --patchSize 13 --poreRadius 4 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 13 --device cuda  --softLabels >> experiments/13PatchSize/PolyUexp2.log; wait;
python3 train.py --patchSize 13 --poreRadius 5 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 13 --device cuda  --softLabels >> experiments/13PatchSize/PolyUexp3.log; wait;
python3 train.py --patchSize 13 --poreRadius 6 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 13 --device cuda --softLabels >> experiments/13PatchSize/PolyUexp4.log; wait;

python3 train.py --patchSize 13 --poreRadius 3 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 13 --device cuda --softLabels >> experiments/13PatchSize/PolyUexp5.log; wait;
python3 train.py --patchSize 13 --poreRadius 4 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 13 --device cuda --softLabels >> experiments/13PatchSize/PolyUexp6.log; wait;
python3 train.py --patchSize 13 --poreRadius 5 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 13 --device cuda --softLabels >> experiments/13PatchSize/PolyUexp7.log; wait;
python3 train.py --patchSize 13 --poreRadius 6 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 13 --device cuda --softLabels >> experiments/13PatchSize/PolyUexp8.log; wait;

python3 train.py --patchSize 13 --poreRadius 3 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 13 --device cuda --softLabels     >> experiments/13PatchSize/PolyUexp9.log; wait;
python3 train.py --patchSize 13 --poreRadius 4 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 13 --device cuda --softLabels   >> experiments/13PatchSize/PolyUexp10.log; wait;
python3 train.py --patchSize 13 --poreRadius 5 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 13 --device cuda --softLabels   >> experiments/13PatchSize/PolyUexp11.log; wait;
python3 train.py --patchSize 13 --poreRadius 6 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 13 --device cuda --softLabels   >> experiments/13PatchSize/PolyUexp12.log; wait;

python3 train.py --patchSize 13 --poreRadius 3 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 13 --device cuda --softLabels   >> experiments/13PatchSize/PolyUexp13.log; wait;
python3 train.py --patchSize 13 --poreRadius 4 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 13 --device cuda --softLabels   >> experiments/13PatchSize/PolyUexp14.log; wait;
python3 train.py --patchSize 13 --poreRadius 5 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 13 --device cuda --softLabels   >> experiments/13PatchSize/PolyUexp15.log; wait;
python3 train.py --patchSize 13 --poreRadius 6 --groundTruth  dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/13PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 13 --device cuda --softLabels   >> experiments/13PatchSize/PolyUexp16.log; wait;