chmod +x scripts/experimentSetUp.sh 
./scripts/experimentSetUp.sh experiments/15PatchSize 

python3 train.py --patchSize 15 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 15 --device cuda  --softLabels    >> experiments/15PatchSize/PolyUexp17.log;
python3 train.py --patchSize 15 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 15 --device cuda  --softLabels    >> experiments/15PatchSize/PolyUexp18.log; wait;
python3 train.py --patchSize 15 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 15 --device cuda  --softLabels    >> experiments/15PatchSize/PolyUexp19.log; wait;
python3 train.py --patchSize 15 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp20.log; wait;

python3 train.py --patchSize 15 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp21.log; wait;
python3 train.py --patchSize 15 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp22.log; wait;
python3 train.py --patchSize 15 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp23.log; wait;
python3 train.py --patchSize 15 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp24.log; wait;

python3 train.py --patchSize 15 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp25.log; wait;
python3 train.py --patchSize 15 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp26.log; wait;
python3 train.py --patchSize 15 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp27.log; wait;
python3 train.py --patchSize 15 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp28.log; wait;

python3 train.py --patchSize 15 --poreRadius 3 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp29.log; wait;
python3 train.py --patchSize 15 --poreRadius 4 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp30.log; wait;
python3 train.py --patchSize 15 --poreRadius 5 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp31.log; wait;
python3 train.py --patchSize 15 --poreRadius 6 --groundTruth dataset --trainingRange $1 --validationRange $2 --testingRange $3 --secondtestingRange $4 --maxPooling True --experimentPath experiments/15PatchSize --testStartProbability 0.1 --testStartNMSUnion 0.1 --residual  --boundingBoxSize 15 --device cuda --softLabels    >> experiments/15PatchSize/PolyUexp32.log; wait;